export type FeatureFlag =
  | 'basic_auth'
  | 'multi_currency'
  | 'basic_reports'
  | 'advanced_reports'
  | 'suppliers'
  | 'customers'
  | 'products'
  | 'export'
  | 'api_access'
  | 'audit_log'
  | 'purchase_orders'
  | 'sales'
  | 'inventory'
  | 'multiple_orgs'
  | 'white_label'
  | 'priority_support';
